import { mkdir, writeFile } from 'node:fs/promises';
const data = [
  [
    'o-que-floresce',
    'o que floresce',
    'jardim',
    ['amor', 'paixao'],
    'pink',
    'você chegou.\na tarde esqueceu de terminar.',
    'estou apaixonado',
  ],
  [
    'inventario-da-ausencia',
    'inventário da ausência',
    'ruinas',
    ['saudade', 'ausencia', 'termino'],
    'violet',
    'na casa vazia,\na luz do corredor\nainda espera alguém.\neu também.',
    'eu sinto sua falta',
  ],
  [
    'a-distancia-das-estrelas',
    'a distância das estrelas',
    'ceu',
    ['esperanca', 'destino', 'distancia'],
    'cyan',
    'o céu não sabe\no nome das nossas ruas.\nainda assim,\nencontra todas as janelas.\n\nhoje deixei a minha aberta.\numa estrela pequena\nentrou sem pedir licença\ne ficou.',
    'ainda tenho esperança',
  ],
  [
    'antes-do-sono',
    'antes do sono',
    'quarto',
    ['confissao', 'medo', 'madrugada'],
    'gold',
    'desligo a última lâmpada.\no quarto guarda seu contorno.\num copo de água\nespera a sede de amanhã.\n\nna cadeira, a roupa do dia.\nno chão, a sombra da cadeira.\nas coisas sabem repousar\nmelhor do que eu.\n\nfecho os olhos.\no escuro não pede explicações.\npela primeira vez hoje,\nisso basta.',
    'tenho medo de perder alguém',
  ],
  [
    'o-peso-do-silencio',
    'o peso do silêncio',
    'abismo',
    ['solidao', 'dor', 'luto'],
    'stone',
    'hoje a casa parece maior.\nas paredes recuaram\num passo que não vi.\nsobrou espaço\nonde antes havia voz.\n\nnão sei o que fazer\ncom uma terça-feira inteira.\na chaleira ferve.\nalguém passa na rua.\no dia continua.\n\ncoloco duas xícaras na mesa.\nguardo uma delas.\neste pequeno movimento\nleva a manhã.\n\nà tarde abro a janela.\nnão porque passou.\nporque o ar precisa entrar.\nporque a planta precisa de água.\nporque estou aqui.\nainda aqui.',
    'estou sozinho',
  ],
  [
    'carta-sem-endereco',
    'carta sem endereço',
    'cartas',
    ['confissao', 'saudade'],
    'gold',
    'escrevi seu nome\nnum envelope vazio.\n\nhá palavras\nque precisam primeiro\naprender a sair de casa.',
    'queria dizer algo que nunca disse',
  ],
  [
    'entre-as-folhas',
    'entre as folhas',
    'jardim',
    ['amor', 'admiracao'],
    'pink',
    'você aponta uma flor.\neu olho para a sua mão.\no jardim acontece\nem dois lugares.',
    'eu gosto de você',
  ],
  [
    'depois-da-chuva',
    'depois da chuva',
    'ceu',
    ['esperanca', 'encontro'],
    'cyan',
    'a chuva deixou\num pequeno céu na calçada.\npassei devagar\npara não pisar nas nuvens.',
    'quero recomeçar',
  ],
  [
    'o-lado-vazio',
    'o lado vazio',
    'ruinas',
    ['termino', 'ausencia', 'rejeicao'],
    'violet',
    'mudei os móveis de lugar.\na cadeira ficou perto da janela.\na mesa, perto da porta.\n\na falta\nnão se moveu.',
    'não fui escolhido',
  ],
  [
    'janela-das-tres',
    'janela das três',
    'quarto',
    ['madrugada', 'confissao', 'solidao'],
    'gold',
    'na janela em frente,\nalguém também está acordado.\n\nnão nos conhecemos.\npor alguns minutos,\no escuro é compartilhado.',
    'não consigo dormir',
  ],
  [
    'sem-mapa',
    'sem mapa',
    'abismo',
    ['solidao', 'dor'],
    'stone',
    'não trouxe respostas.\nsó um lugar para sentar\nenquanto a noite passa.',
    'nem eu sei',
  ],
  [
    'o-que-nao-enviei',
    'o que não enviei',
    'cartas',
    ['confissao', 'medo', 'amor'],
    'gold',
    'o papel terminou.\no que eu queria dizer, não.',
    'não sei como dizer',
  ],
];
await mkdir('content/poems', { recursive: true });
for (const [
  index,
  [slug, title, place, tags, accent, content, phrase],
] of data.entries()) {
  const poem = {
    id: `demo-${String(index + 1).padStart(2, '0')}`,
    slug,
    title,
    excerpt: content.split('\n').filter(Boolean).slice(0, 3).join('\n'),
    content,
    place,
    tags,
    date: `2026-08-${String(24 - index).padStart(2, '0')}`,
    featured: index < 4,
    mood: place === 'jardim' ? 'romantic' : 'contemplative',
    accent,
    series: [1, 2, 5, 8].includes(index) ? 'Em português se diz' : null,
    language: 'pt-BR',
    demo: true,
    phrase,
  };
  await writeFile(
    `content/poems/${String(slug)}.json`,
    JSON.stringify(poem, null, 2) + '\n',
  );
}
